### ISSUE TITLE
[UI] Sortie text does not fit within text box

### ISSUE THREAD

**Issue by scorchgid** [WFCD/navis#28] opened 2019-06-25 22:43 UTC
Please see image inserted and excuse the lazyness of not cropping.

Essentially the first sortie mission's text is too long for the box to fit in I've seen this occur with other sorties as well on the app.

I am currently on your beta channel but I've seen this occur on stable as well.

Phone model: OP3T 
OS: Android 9

![image](https://i.imgur.com/fdfoqQX.jpg) 

Good luck.  

Ps please ignore the yellow line in the bottom left-hand corner as that's nothing to do with your app.

**Comment by SlayerOrnstein** [comment] 2019-06-26 00:42
well I can't really say what the cause would be since my Nexus 5 or the emulator are showing this problem. But I tweaked the design a bit, if you want to see if it fits now [apk](https://www.dropbox.com/s/l146i9s7m0jrf7h/app-release.apk?dl=0)

**Comment by SlayerOrnstein** [comment] 2019-07-23 01:26
well enough time has passed and safe to say this was probably already fixed so closing for now

**Closed by SlayerOrnstein** 2019-07-23 01:26 UTC
